# Generated by Django 5.0.2 on 2024-02-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_note_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='shared_with',
        ),
    ]
