# Generated by Django 5.0.2 on 2024-02-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_note_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created_by',
            new_name='user',
        ),
    ]
